### ISSUE TITLE
训练时accelerate报错

### ISSUE THREAD

**Issue by SYZhang0805** [baofff/U-ViT#12]
我在训练的时候，accelerate报错gpu_ids找不到
Traceback (most recent call last):
  File "/opt/anaconda3/envs/UVIT/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/UVIT/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/anaconda3/envs/UVIT/lib/python3.8/site-packages/accelerate/commands/launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/opt/anaconda3/envs/UVIT/lib/python3.8/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/opt/anaconda3/envs/UVIT/lib/python3.8/site-packages/accelerate/commands/config/config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'gpu_ids'

**Comment by fikry102** [comment]
我一开始也遇到了同样的错误，然后再执行accelerate config配置一下之后就好了，你可以尝试一下

**Comment by yhy-2000** [comment]
> 我一开始也遇到了同样的错误，然后再执行accelerate config配置一下之后就好了，你可以尝试一下
我在运行时候遇到了File "/home/yhyaaa/.local/lib/python3.9/site-packages/accelerate/data_loader.py", line 350, in __iter__ self.gradient_state._iterate_samples_seen(find_batch_size(current_batch)) AttributeError: 'GradientState' object has no attribute '_iterate_samples_seen'的错误，感觉应该是环境问题，可以分享一下你的环境配置吗？
