### ISSUE TITLE
AttributeError: 'GradientState' object has no attribute '_iterate_samples_seen'

### ISSUE THREAD

**Issue by yhy-2000** [baofff/U-ViT#22]
Hello fan,
I have the same package version as README.md, but when I run 'accelerate launch --multi_gpu --num_processes 1 --mixed_precision fp16 train_t2i_discrete.py     --config=configs/mscoco_uvit_small.py     --config.nnet.depth=16', I met the error as follows:
`
Traceback (most recent call last):
  File "/home/yhyaaa/U-ViT/train_t2i_discrete.py", line 333, in <module>
    app.run(main)
  File "/home/yhyaaa/.local/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/yhyaaa/.local/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/yhyaaa/U-ViT/train_t2i_discrete.py", line 324, in main
    train(config)
  File "/home/yhyaaa/U-ViT/train_t2i_discrete.py", line 237, in train
    batch = tree_map(lambda x: x.to(device), next(data_generator))
  File "/home/yhyaaa/U-ViT/train_t2i_discrete.py", line 154, in get_data_generator
    for data in tqdm(train_dataset_loader, disable=not accelerator.is_main_process, desc='epoch'):
  File "/home/yhyaaa/.local/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/yhyaaa/.local/lib/python3.9/site-packages/accelerate/data_loader.py", line 350, in __iter__
    self.gradient_state._iterate_samples_seen(find_batch_size(current_batch))
AttributeError: 'GradientState' object has no attribute '_iterate_samples_seen'
`
My environment is:
`
python=3.10.0
cuda=12.3
1*A100
`
Could you please give some suggestions?

**Comment by yhy-2000** [comment]
Fix.
When I run pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu116, Conda will install torch==2.3.0 in my environment(cuda12.3). After I explicitly set the torch version to 1.13.1, like pip install torch==1.13.1 torchvision --extra-index-url https://download.pytorch.org/whl/cu116, it will install torch 1.13.1+cu116, and this issue disappears.
